# Generated by Django 4.2 on 2023-06-07 12:00

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Fav_Stores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Fav_Store',
                'verbose_name_plural': 'Fav_Stores',
            },
        ),
        migrations.CreateModel(
            name='Followed_Stores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Followed_Store',
                'verbose_name_plural': 'Followed_Stores',
            },
        ),
        migrations.CreateModel(
            name='Liked_Posts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Liked_Post',
                'verbose_name_plural': 'Liked_Posts',
            },
        ),
        migrations.CreateModel(
            name='Rated_Stores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Rated_Store',
                'verbose_name_plural': 'Rated_Stores',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=10)),
                ('address', models.CharField(default='', max_length=250)),
                ('is_owner', models.BooleanField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=150)),
                ('category', models.CharField(max_length=20)),
                ('opening', models.TimeField()),
                ('closing', models.TimeField()),
                ('phone', models.CharField(max_length=10)),
                ('address', models.CharField(max_length=250)),
                ('facebook', models.CharField(max_length=50)),
                ('insta', models.CharField(max_length=50)),
                ('profile_photo', models.ImageField(upload_to='photos/profiles/%Y/%m/%d/')),
                ('cover_photo', models.ImageField(upload_to='photos/covers/%Y/%m/%d/')),
                ('rate', models.FloatField()),
                ('creation_date', models.DateTimeField(default=datetime.datetime.now)),
                ('fav', models.ManyToManyField(related_name='favourites', through='app.Fav_Stores', to='app.userprofile')),
                ('followed', models.ManyToManyField(related_name='followed', through='app.Followed_Stores', to='app.userprofile')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.userprofile')),
                ('rated', models.ManyToManyField(related_name='rated', through='app.Rated_Stores', to='app.userprofile')),
            ],
        ),
        migrations.AddField(
            model_name='rated_stores',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.store'),
        ),
        migrations.AddField(
            model_name='rated_stores',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.userprofile'),
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=150)),
                ('creation_date', models.DateTimeField(default=datetime.datetime.now)),
                ('price', models.FloatField()),
                ('photos', models.ImageField(upload_to='photos/posts/%Y/%m/%d/')),
                ('like_posts', models.ManyToManyField(related_name='liked', through='app.Liked_Posts', to='app.userprofile')),
                ('owner', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='app.store')),
            ],
        ),
        migrations.AddField(
            model_name='liked_posts',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.post'),
        ),
        migrations.AddField(
            model_name='liked_posts',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.userprofile'),
        ),
        migrations.AddField(
            model_name='followed_stores',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.store'),
        ),
        migrations.AddField(
            model_name='followed_stores',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.userprofile'),
        ),
        migrations.AddField(
            model_name='fav_stores',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.store'),
        ),
        migrations.AddField(
            model_name='fav_stores',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.userprofile'),
        ),
    ]
