# Generated by Django 4.2 on 2023-06-29 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='closing',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='store',
            name='opening',
            field=models.CharField(max_length=10),
        ),
    ]
