# Generated by Django 4.2 on 2023-07-13 14:41

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_post_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inbox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=500)),
                ('photo', models.ImageField(upload_to='photos/Inbox/%Y/%m/%d/')),
                ('creation_date', models.DateTimeField(default=datetime.datetime.now)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.userprofile')),
            ],
            options={
                'verbose_name': 'inbox',
                'verbose_name_plural': 'Inboxes',
            },
        ),
    ]
