# Generated by Django 4.2 on 2023-07-15 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_inbox_is_done'),
    ]

    operations = [
        migrations.AddField(
            model_name='inbox',
            name='reply',
            field=models.CharField(default='', max_length=500),
        ),
    ]
