# Generated by Django 4.2 on 2023-07-21 11:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_inbox_reply_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inbox',
            name='reply_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
