# Generated by Django 4.2 on 2023-07-25 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_alter_inbox_reply_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='address',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='store',
            name='closing',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='store',
            name='cover_photo',
            field=models.ImageField(blank=True, upload_to='photos/covers/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='store',
            name='description',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='store',
            name='facebook',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='store',
            name='insta',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='store',
            name='opening',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='store',
            name='phone',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='store',
            name='profile_photo',
            field=models.ImageField(blank=True, upload_to='photos/profiles/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='store',
            name='rate',
            field=models.FloatField(blank=True),
        ),
    ]
